version: '3.2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      # - /usr/app/node_modules
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/pdct
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres,
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdct